version: "3.9"
services:  
  redis:
    image: alpine:latest
  k3s:
    image: alpine:latest
  elasticsearch:
    image: alpine:latest
  integration-module:
    image: alpine:latest
  postgres:
    image: alpine:latest
  backend:
    image: alpine:latest
    depends_on:
      - redis
      - k3s
      - elasticsearch
      - postgres
  gateway:
    image: alpine:latest
  frontend:
    image: alpine:latest
  helper:
    image: alpine:latest
    command:
      - sh
      - -c
      - "echo 'Please use the ./launcher script instead'  ; exit 0"

volumes:
  postgresData: {}
  redisData: {}
  elasticData: {}
  ucloudData: {}
  ucloudFiles: {}
  k3sConfig: {}
  k3sData: {}
  imData: {}
  imGradle: {}
  imKonan: {}
  backendKonan: {}
  backendGradle: {}
  m2Repo: {}