version: "3.9"
services:
  redis:
    image: redis:5.0.9
    volumes:
      - redisData:/data
    hostname: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    hostname: elasticsearch

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgresData:/var/lib/postgresql/data
    ports:
    - 35432:5432
    hostname: postgres

  k3s:
    image: rancher/k3s:v1.16.13-rc3-k3s1-amd64
    privileged: true
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
    - ucloudFiles:/mnt/cephfs
    - k3sConfig:/output
    - k3sData:/var/lib/rancher/k3s
    command:
      - server
    hostname: k3s

  backend:
    image: dreg.cloud.sdu.dk/ucloud/ucloud:2021.2.0-storage5
    user: root
    command:
      - /opt/service/bin/service
      - --dev
      - --config-dir
      - /etc/ucloud
    volumes:
      - ucloudData:/etc/ucloud
      - ucloudFiles:/mnt/cephfs
      - k3sConfig:/mnt/k3s
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - redis
      - postgres
      - elasticsearch
      - k3s
    hostname: backend

  frontend:
    image: dreg.cloud.sdu.dk/ucloud/webclient:0.50.0-storage6
    hostname: frontend

